// Фиксированные словари тегов — те же списки проверяет scripts/validate-dataset.mjs.

export const GRAMMAR_TAGS = [
  "present-simple",
  "present-continuous",
  "present-continuous-future",
  "past-simple",
  "past-continuous",
  "present-perfect",
  "present-perfect-continuous",
  "past-perfect",
  "past-perfect-continuous",
  "future-will",
  "going-to",
  "future-continuous",
  "future-perfect",
  "future-perfect-continuous",
  "question",
  "indirect-question",
  "tag-question",
  "short-answer",
  "negation",
  "imperative",
  "modal",
  "conditional-0",
  "conditional-1",
  "conditional-2",
  "conditional-3",
  "conditional-mixed",
  "gerund",
  "infinitive",
  "to-preposition",
  "bare-infinitive",
  "preposition",
  "phrasal-verb",
  "collocation",
  "article",
  "quantifier",
  "countable-uncountable",
  "comparative",
  "superlative",
  "relative-clause",
  "passive",
  "used-to",
  "be-used-to",
  "would-like",
  "there-is",
  "word-order",
  "stop-remember-try",
  "look-forward-to",
  "feel-like",
  "time-preposition",
  "place-preposition",
  "movement-preposition",
  "for-since",
  "by-until",
  "want-someone-to",
  "reported-speech"
] as const;

export const TOPIC_TAGS = [
  "acquaintance",
  "texting",
  "small-talk",
  "humor",
  "dating",
  "relationships",
  "past-relationships",
  "feelings",
  "family",
  "work",
  "travel",
  "daily-life",
  "food",
  "friends",
  "interests",
  "deep-talk",
  "plans",
  "lifestyle",
  "communication"
] as const;

// Группы для кнопок-фильтров по грамматике
export const GRAMMAR_FILTERS: { key: string; label: string; tags: string[] }[] = [
  { key: "questions", label: "Вопросы", tags: ["question", "tag-question"] },
  { key: "present-simple", label: "Present Simple", tags: ["present-simple"] },
  { key: "present-continuous", label: "Present Continuous", tags: ["present-continuous", "present-continuous-future"] },
  { key: "past", label: "Past", tags: ["past-simple", "past-continuous", "past-perfect", "past-perfect-continuous", "used-to"] },
  { key: "perfect", label: "Perfect", tags: ["present-perfect", "present-perfect-continuous", "past-perfect", "past-perfect-continuous", "future-perfect", "future-perfect-continuous"] },
  { key: "future", label: "Future", tags: ["future-will", "going-to", "future-continuous", "future-perfect", "future-perfect-continuous", "present-continuous-future"] },
  { key: "ing", label: "-ing", tags: ["gerund", "look-forward-to", "be-used-to", "feel-like", "present-continuous", "present-perfect-continuous", "past-continuous"] },
  { key: "prepositions", label: "Предлоги", tags: ["preposition", "time-preposition", "place-preposition", "movement-preposition", "to-preposition", "for-since", "by-until"] },
  { key: "conditionals", label: "Conditionals", tags: ["conditional-0", "conditional-1", "conditional-2", "conditional-3", "conditional-mixed"] },
  { key: "modals", label: "Modals", tags: ["modal"] },
  { key: "indirect", label: "Indirect Questions", tags: ["indirect-question"] }
];

// Группы для кнопок-фильтров по темам
export const TOPIC_FILTERS: { key: string; label: string; tags: string[] }[] = [
  { key: "communication", label: "Общение", tags: ["communication", "texting", "small-talk", "humor"] },
  { key: "acquaintance", label: "Знакомства", tags: ["acquaintance", "dating"] },
  { key: "relationships", label: "Отношения", tags: ["relationships", "past-relationships", "feelings"] },
  { key: "travel", label: "Путешествия", tags: ["travel"] },
  { key: "work", label: "Работа", tags: ["work"] },
  { key: "family", label: "Семья", tags: ["family", "friends"] },
  { key: "daily", label: "Повседневность", tags: ["daily-life", "food", "lifestyle", "plans"] },
  { key: "interests", label: "Интересы", tags: ["interests"] },
  { key: "deep", label: "Глубокие разговоры", tags: ["deep-talk"] }
];
